# Generated by Django 4.1 on 2024-05-01 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contents/files/')),
                ('date_added', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'contents',
            },
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='dining/')),
                ('price_less_500', models.CharField(blank=True, max_length=100, null=True)),
                ('price_500', models.CharField(blank=True, max_length=100, null=True)),
                ('price_1000', models.CharField(blank=True, max_length=100, null=True)),
                ('price_1500', models.CharField(blank=True, max_length=100, null=True)),
                ('price_2000_plus', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'product_categories',
            },
        ),
        migrations.AddField(
            model_name='extra',
            name='type',
            field=models.CharField(default='extra', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.CharField(max_length=100)),
                ('compare_at_price', models.CharField(blank=True, max_length=100, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='products/')),
                ('is_published', models.BooleanField(blank=True, default=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
