# Generated by Django 4.1 on 2024-05-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_content_dining_productcategory_extra_type_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='decoration',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='dining',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='entertainment',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='extra',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
