# Generated by Django 4.1 on 2024-05-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_accommodation_slug_decoration_slug_destination_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('provider_name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=10)),
                ('compare_at_price', models.CharField(blank=True, max_length=10, null=True)),
                ('image', models.ImageField(upload_to='service_img/')),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
