# Generated by Django 4.1 on 2024-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_contact_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='meal_preferences',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='number_of_guests',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
