# Generated by Django 4.1 on 2024-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_services_alter_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='services',
            name='provider_company',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='provider_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
