# Generated by Django 4.1 on 2024-05-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_contact_meal_preferences_contact_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
