# Generated by Django 4.1 on 2024-05-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_contact_message'),
        ('backend', '0008_cart_custompackage_carttotal_cartitem_cart_items_and_more'),
    ]

    operations = [
    ]
