# Generated by Django 4.1 on 2024-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_merge_20240505_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='services',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
