# Generated by Django 4.1 on 2024-05-05 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_package_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='accomodation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.accommodation'),
        ),
        migrations.AlterField(
            model_name='package',
            name='decoration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.decoration'),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.destination'),
        ),
        migrations.AlterField(
            model_name='package',
            name='entertainment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.entertainment'),
        ),
        migrations.AlterField(
            model_name='package',
            name='extra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.extra'),
        ),
        migrations.AlterField(
            model_name='package',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.menu'),
        ),
    ]
