# Generated by Django 4.1 on 2024-05-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_package_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='packages',
            field=models.ManyToManyField(blank=True, null=True, to='backend.package'),
        ),
        migrations.AddField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='backend.products'),
        ),
    ]
