# Generated by Django 4.1 on 2024-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_remove_cart_items_cart_packages_cart_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('post_code', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('order_notes', models.TextField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(default='cash on delivery', max_length=255)),
                ('packages', models.ManyToManyField(blank=True, null=True, to='backend.package')),
                ('products', models.ManyToManyField(blank=True, null=True, to='backend.products')),
            ],
        ),
    ]
