# Generated by Django 4.1 on 2024-05-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(blank=True, default='cash on delivery', max_length=255, null=True),
        ),
    ]
