# Generated by Django 4.1 on 2024-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name',
            field=models.CharField(default='LUXARY PACKAGE', max_length=255),
            preserve_default=False,
        ),
    ]
