# Generated by Django 4.1 on 2024-05-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='entertainment',
        ),
        migrations.AddField(
            model_name='package',
            name='entertainment',
            field=models.ManyToManyField(blank=True, null=True, to='backend.entertainment'),
        ),
    ]
